name: Tests

on: [push]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macOS-latest]
        python: [ '3.5', '3.6', '3.7' ]
    name: python${{ matrix.python }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - name: Install test dependencies
        run: pip install tox codecov
      - name: Run tests
        run: tox
        env:
          TOXENV: py
